[#ftl]
[@b.head/]
[@b.toolbar title="职称"]bar.addBack();[/@]
  [@b.form action=b.rest.save(professionalTitle) theme="list"]
    [@b.textfield name="professionalTitle.code" label="代码" value="${professionalTitle.code!}" required="true" maxlength="20"/]
    [@b.textfield name="professionalTitle.name" label="名称" value="${professionalTitle.name!}" required="true" maxlength="20"/]
    [@b.textfield name="professionalTitle.enName" label="英文名" value="${professionalTitle.enName!}" maxlength="100"/]
    [@b.select name="professionalTitle.grade.id" label="级别" items=grades value=professionalTitle.grade! required="true" empty="..."/]
    [@b.startend label="有效期"
      name="professionalTitle.beginOn,professionalTitle.endOn" required="true,false"
      start=professionalTitle.beginOn end=professionalTitle.endOn format="date"/]
    [@b.textfield name="professionalTitle.remark" label="备注" value="${professionalTitle.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
