[#ftl]
[@b.head/]
[@b.toolbar title="修改毕业界别"]bar.addBack();[/@]
  [@b.form action=b.rest.save(graduateSeason) theme="list"]
    [@b.textfield name="graduateSeason.code" label="代码" value=graduateSeason.code! required="true" maxlength="20" placeholder="yyyy"/]
    [@b.textfield name="graduateSeason.name" label="名称" value=graduateSeason.name! required="true" maxlength="20" placeholder="yyyy届"/]
    [@b.textfield name="graduateSeason.graduateYear" label="毕业年份" value=graduateSeason.graduateYear! maxlength="100"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
