[#ftl]
[@b.nav class="nav-tabs nav-tabs-compact"]
  [@b.navitem href="semester"]学年学期[/@]
  [@b.navitem href="holiday"]假日调课[/@]
  [@b.navitem href="calendar"]日历方案[/@]
  [@b.navitem href="calendar-stage"]学期阶段[/@]
[/@]
