[#ftl]
[@b.head/]
[@b.toolbar title="修改课程模块"]bar.addBack();[/@]
  [@b.form action=b.rest.save(courseModule) theme="list"]
    [@b.textfield name="courseModule.code" label="代码" value="${courseModule.code!}" required="true" maxlength="20"/]
    [@b.textfield name="courseModule.name" label="名称" value="${courseModule.name!}" required="true" maxlength="20"/]
    [@b.textfield name="courseModule.enName" label="英文名" value="${courseModule.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="courseModule.beginOn,courseModule.endOn" required="true,false"
      start=courseModule.beginOn end=courseModule.endOn format="date"/]
    [@b.textfield name="courseModule.remark" label="备注" value="${courseModule.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
