[#ftl]
[@b.head/]
[@b.toolbar title="新建学历类型"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!save" theme="list"]
    [@b.textfield name="education.code" label="代码" value="${education.code!}" required="true" maxlength="20"/]
    [@b.textfield name="education.name" label="名称" value="${education.name!}" required="true" maxlength="20"/]
    [@b.textfield name="education.enName" label="英文名称" value="${education.enName!}" maxlength="100"/]
    [@b.startend label="生效失效时间" 
      name="education.beginOn,education.endOn" required="false,false" 
      start=education.beginOn end=education.endOn format="date"/]
    [@b.textfield name="education.remark" label="备注" value="${education.remark!}" maxlength="30"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]