[#ftl]
[@b.head/]
[@b.toolbar title="修改代码类别"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if codeCategory.persisted]!update?id=${codeCategory.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
      [@b.textfield name="codeCategory.name" label="代码类名" value="${codeCategory.name!}" required="true" maxlength="50"/]
      [@b.textfield name="codeCategory.indexno" label="序号" value="${codeCategory.indexno!}" required="true" maxlength="50"/]
      [@b.select name="codeCategory.parent.id" label="父级菜单" value="${(codeCategory.parent.id)!}"
                 style="width:200px;" href=urp.service("/base/code/code-categories") empty="..."/]
      [@b.formfoot]
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
      [/@]
    [/@]
  [/@]
[@b.foot/]
