[#ftl]
[@b.head/]
[@b.toolbar title="添加教职工信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(staff) theme="list"]
    [@b.textfield name="staff.code" label="职工号" value=staff.code! required="true" style="width:100px;" maxlength="20"/]
    [@b.textfield name="staff.name" label="姓名" id="name" value=staff.name! required="true" style="width:100px;" maxlength="20"/]
    [@b.radios name="staff.gender.id" label="性别" value=staff.gender! required="true"  items=genders /]
    [@b.select name="staff.idType.id" label="证件类型" value="1" required="true"  items=idTypes  empty="..." /]
    [@b.textfield name="staff.idNumber" label="证件号码" value=staff.idNumber! required=extraRequired?seq_contains("idNumber")?c maxlength="20"/]

    [@b.select name="staff.staffType.id" label="教职工类别" value=staff.staffType! required="true"  items=staffTypes/]
    [@b.select name="staff.department.id" label="所在部门" value=staff.department! required="true" style="width:200px;" items=departments empty="..."/]
    [@b.radios label="是否在编"  name="staff.formalHr" value=staff.formalHr items="1:common.yes,0:common.no" required="true"/]
    [@b.radios label="是否外聘"  name="staff.external" value=staff.external items="1:common.yes,0:common.no" required="true"/]
    [@b.radios label="是否兼职"  name="staff.parttime" value=staff.parttime items="1:common.yes,0:common.no" required="true"/]
    [@b.textfield label="移动电话"  name="staff.mobile" value=staff.mobile! required=extraRequired?seq_contains("mobile")?c /]
    [@b.startend label="在校时间" name="staff.beginOn,staff.endOn" required="true,false" start=staff.beginOn end=staff.endOn format="date"/]
    [@b.select name="staff.status.id" label="在职状态" value=staff.status! required="true"  items=statuses/]
    [@b.radios label="是否任教"  name="isTeacher" value="1" items="1:common.yes,0:common.no" required="true"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
