[#ftl]
[@b.head/]
[@b.toolbar title="修改教室类型"]bar.addBack();[/@]
  [@b.form action=b.rest.save(classroomType) theme="list"]
    [@b.textfield name="classroomType.code" label="代码" value="${classroomType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="classroomType.name" label="名称" value="${classroomType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="classroomType.enName" label="英文名称" value="${classroomType.enName!}" maxlength="100"/]
    [@b.startend label="有效期限"
      name="classroomType.beginOn,classroomType.endOn" required="true,false"
      start=classroomType.beginOn end=classroomType.endOn format="date"/]
    [@b.textfield name="classroomType.remark" label="备注" value="${classroomType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
