[#ftl]
[@b.head/]
[@b.toolbar title="修改课程种类代码"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if courseAssessCategory.persisted]!update?id=${courseAssessCategory.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="courseAssessCategory.code" label="代码" value="${courseAssessCategory.code!}" required="true" maxlength="20"/]
    [@b.textfield name="courseAssessCategory.name" label="名称" value="${courseAssessCategory.name!}" required="true" maxlength="20"/]
    [@b.textfield name="courseAssessCategory.enName" label="英文名" value="${courseAssessCategory.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="courseAssessCategory.beginOn,courseAssessCategory.endOn" required="true,false"
      start=courseAssessCategory.beginOn end=courseAssessCategory.endOn format="date"/]
    [@b.textfield name="courseAssessCategory.remark" label="备注" value="${courseAssessCategory.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
