[#ftl]
[@b.head/]
  [@b.toolbar title="批量添加教材"]bar.addBack();[/@]
  [@b.form action="!batchAddForm" theme="list"]
    [@b.textarea name="isbn" label="ISBN" value="${Parameters['isbn']!}" required="true" maxlength="30000" rows="10" cols="80"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="查询"/]
    [/@]
  [/@]
  [#if isbnList??]
  [@b.form action="!batchAdd" theme="list"]
    [@b.grid items=isbnDatas var="book"]
      [@b.row]
        [@b.boxcol property="isbn" checked=book.name?? display=book.name??/]
        [@b.col title="ISBN" width="15%"]${book.isbn}[/@]
        [@b.col title="图书信息" ][#if book.name??]${book.name} ${book.author!} ${book.press!} ${book.publishedOn!} ${book.edition!}[#else]查无此书[/#if][/@]
      [/@]
    [/@]
    [@b.formfoot]
      [@b.submit value="添加"/]
    [/@]
  [/@]
  [/#if]
[@b.foot/]
