[#ftl]
[@b.head/]
[@b.tabs]
   [@b.tab href="/admin/edu/textbook!innerIndex" label="教材信息" active="true"/]
   [@b.tab href="/admin/edu/course-textbook" label="推荐教材" /]
   [@b.tab href="/admin/edu/code/press/search" label="出版社" /]
   [@b.tab href="/admin/edu/code/press-grade/search" label="出版社级别" /]
   [@b.tab href="/admin/edu/code/book-category/search" label="图书分类" /]
   [@b.tab href="/admin/edu/code/book-type/search" label="教材类型" /]
   [@b.tab href="/admin/edu/code/book-award-type/search" label="教材获奖类型" /]
[/@]
[@b.foot/]
