[#ftl]
[@b.head/]
[@b.toolbar title="修改课时类别代码"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(teachingNature) theme="list" ]
    [@b.textfield name="teachingNature.code" label="代码" value="${teachingNature.code!}" required="true" maxlength="20"/]
    [@b.textfield name="teachingNature.name" label="名称" value="${teachingNature.name!}" required="true" maxlength="20"/]
    [@b.textfield name="teachingNature.enName" label="英文名" value="${teachingNature.enName!}" maxlength="100"/]
    [#assign categoryTitles={}/]
    [#list categories as ca]
      [#assign categoryTitles=categoryTitles+{'${ca}':'${ca.title}'}/]
    [/#list]
    [@b.radios label="分类" name="teachingNature.category" items=categoryTitles value=(teachingNature.category?string)!'Theory'/]
    [@b.startend label="有效期"
      name="teachingNature.beginOn,teachingNature.endOn" required="true,false"
      start=teachingNature.beginOn end=teachingNature.endOn format="date"/]
    [@b.textfield name="teachingNature.remark" label="备注" value="${teachingNature.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
