[#ftl]
[@b.head/]
[@b.grid items=codees var="code"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="15%" property="code" title="代码"]${code.code}[/@]
    [@b.col width="15%" property="name" title="名称"][@b.a href="!info?id=${code.id}"]${code.name}[/@][/@]
    [@b.col property="enName" title="英文名"]${code.enName!}[/@]
    [@b.col width="8%" property="attended" title="是否参加考试"]${(code.attended?string("是","否"))!}[/@]
    [@b.col width="8%" property="hasDeferred" title="是否缓考"]${(code.hasDeferred?string("是","否"))!}[/@]
    [@b.col width="9%" property="cheating" title="是否有作弊行为"]${(code.cheating?string("是","否"))!}[/@]
    [@b.col width="10%" property="beginOn" title="生效日期"]${code.beginOn!}[/@]
    [@b.col width="10%" property="endOn" title="失效日期"]${code.endOn!}[/@]
  [/@]
[/@]
[@b.foot/]
