[#ftl]
[@b.head/]
[@b.toolbar title="部门变迁信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(transition) theme="list"]
    [@b.select name="from.id" label="原部门" value=transition.from! items=departments required="true"/]
    [@b.select name="to.id" label="目标部门" value=transition.to! items=departments required="true"/]
    [@b.date label="生效日期" name="transition.effectiveOn" value=transition.effectiveOn! required="true"/]
    [@b.textarea label="备注" name="transition.remark" value=transition.remark! rows="3" maxlength="200"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
