[#ftl]
[@b.head/]
[@b.toolbar title="修改学籍异动原因"]bar.addBack();[/@]
  [@b.form action=b.rest.save(stdAlterReason) theme="list"]
    [@b.textfield name="stdAlterReason.code" label="代码" value="${stdAlterReason.code!}" required="true" maxlength="20"/]
    [@b.textfield name="stdAlterReason.name" label="名称" value="${stdAlterReason.name!}" required="true" maxlength="20"/]
    [@b.textfield name="stdAlterReason.enName" label="英文名" value="${stdAlterReason.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="stdAlterReason.beginOn,stdAlterReason.endOn" required="true,false"
      start=stdAlterReason.beginOn end=stdAlterReason.endOn format="date"/]
    [@b.textfield name="stdAlterReason.remark" label="备注" value="${stdAlterReason.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
