[#ftl]
[@b.head/]
[@b.grid items=courses var="course"]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="code" title="代码"/]
    [@b.col width="20%" property="name" title="名称"][@b.a href="!info?id=${course.id}"]${course.name}[/@][/@]
    [@b.col width="5%" property="defaultCredits" title="学分"/]
    [@b.col width="5%" property="creditHours" title="学时"/]
    [@b.col width="5%" property="weekHours" title="周课时"/]
    [@b.col width="5%" property="weeks" title="周数"/]
    [@b.col width="20%" property="department.name" title="课程所属院系"/]
    [@b.col width="20%" property="courseType.name" title="课程类型"/]
    [@b.col width="10%" property="examMode.name" title="考核方式"/]
  [/@]
  [/@]
[@b.foot/]
