[@b.head/]
[@b.toolbar title="修改民族信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(code) theme="list"]
    [@b.textfield name="code.code" label="代码" value=code.code! required="true" maxlength="20"/]
    [@b.textfield name="code.name" label="名称" value=code.name! required="true" maxlength="200"/]
    [@b.textfield name="code.enName" label="英文名称" value=code.enName! maxlength="200"/]
    [@b.textfield name="code.alphaCode" label="字母代码" value=code.alphaCode! required="true" maxlength="3"/]
    [@b.startend label="有效期限"
      name="code.beginOn,code.endOn" required="true,false"
      start=code.beginOn end=code.endOn format="date"/]
    [@b.textfield name="code.remark" label="备注" value="${code.remark!}" maxlength="30"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
