[#ftl]
[@b.head/]
[@b.grid items=courseTypes var="courseType"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="code" title="代码"]${courseType.code}[/@]
    [@b.col width="20%" property="name" title="名称"][@b.a href="!info?id=${courseType.id}"]${courseType.name}[/@][/@]
    [@b.col width="20%" property="enName" title="英文名"]${courseType.enName!}[/@]
    [@b.col width="8%" property="theoretical" title="是否实践课"]${(courseType.practical?string("是","否"))!}[/@]
    [@b.col width="8%" property="major" title="是否专业课"]${(courseType.major?string("是","否"))!}[/@]
    [@b.col width="9%" property="optional" title="是否选修课"]${(courseType.optional?string("是","否"))!}[/@]
    [@b.col width="20%" property="beginOn" title="有效期"]${courseType.beginOn!}~${courseType.endOn!}[/@]
  [/@]
[/@]
[@b.foot/]
