[#ftl]
[@b.head/]
[@b.toolbar title="新建性别类型"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!save" theme="list"]
    [@b.textfield name="gender.code" label="代码" value="${gender.code!}" required="true" maxlength="20"/]
    [@b.textfield name="gender.name" label="性别名称" value="${gender.name!}" required="true" maxlength="20"/]
    [@b.textfield name="gender.enName" label="英文名称" value="${gender.enName!}" maxlength="100"/]
    [@b.startend label="开始结束时间" 
      name="gender.beginOn,gender.endOn" required="false,false" 
      start=gender.beginOn end=gender.endOn format="date"/]
    [@b.textfield name="gender.remark" label="备注" value="${gender.remark!}" maxlength="30"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]