[#ftl]
[@b.head/]
[@b.toolbar title="修改学年度"]bar.addBack();[/@]
  [@b.form action=b.rest.save(schoolYear) theme="list"]
    [@b.textfield name="schoolYear.name" label="名称" value=schoolYear.name! required="true" maxlength="10"/]
    [@b.textfield name="schoolYear.startYear" label="起始年份" value=schoolYear.startYear! required="true" maxlength="10"/]
    [@b.select name="schoolYear.calendar.id" label="日历方案" value=schoolYear.calendar! items=calendars required="true"/]
    [@b.radios label="是否归档"  name="schoolYear.archived" value=schoolYear.archived items="1:common.yes,0:common.no"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
