[#ftl]
[@b.head/]
[@b.grid items=staffs var="staff" theme="mini"]
  [@b.row]
    [@b.col width="10%" property="code" title="工号"]${staff.code}[/@]
    [@b.col width="10%" property="name" title="姓名"]
      [@b.a href="!info?id=${staff.id}" target="_blank"]
        <span title="${staff.beginOn!}~${staff.endOn!}">${staff.name}</span>
      [/@]
    [/@]
    [@b.col width="8%" property="gender.name" title="性别"/]
    [@b.col width="10%" title="出生年月"]
      ${(staff.birthday?string("yyyy-MM"))!}
    [/@]
    [@b.col property="department.name" title="院系"]${(staff.department.name)!}[/@]
    [@b.col width="15%" property="degree.name" title="学位"]
      [#if staff.degree??]${staff.degree.name?replace("学位","")}[#else]--[/#if]
    [/@]
    [@b.col width="15%" property="title.name" title="职称"]${(staff.title.name)!}[/@]
    [@b.col property="tutorType.name" width="18%" title="导师类别"/]
  [/@]
[/@]
[@b.foot/]
