[@b.nav class="nav-tabs nav-tabs-compact"]
  [@b.navitem href="tutor"]导师信息[/@]
  [@b.navitem href="tutor-major"]研究领域[/@]
  [@b.navitem href="profile"]导师简介[/@]
  [#if ems.permitted("/admin/hr/tutor-stat")]
  [@b.navitem href="tutor-stat!major"]导师统计[/@]
  [/#if]
  [@b.navitem href="tutor-stat!std"]带学生统计[/@]
[/@]
