[#ftl]
[@b.head/]
[@b.toolbar title="修改性别类型"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if gender.id??]!update?id=${gender.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="gender.code" label="代码" value="${gender.code!}" required="true" maxlength="20"/]
    [@b.textfield name="gender.name" label="名称" value="${gender.name!}" required="true" maxlength="20"/]
    [@b.textfield name="gender.enName" label="英文名称" value="${gender.enName!}" maxlength="100"/]
    [@b.startend label="生效失效时间" 
      name="gender.beginOn,gender.endOn" required="false,false" 
      start=gender.beginOn end=gender.endOn format="date"/]
    [@b.textfield name="gender.remark" label="备注" value="${gender.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]