[#ftl]
[@b.head/]
[@b.toolbar title="修改课程类别"]bar.addBack();[/@]
  [#assign sa][#if code.persisted]!update?id=${code.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="code.code" label="代码" value="${code.code!}" required="true" maxlength="20"/]
    [@b.textfield name="code.name" label="名称" value="${code.name!}" required="true" maxlength="20"/]
    [@b.textfield name="code.enName" label="英文名" value="${code.enName!}" maxlength="100"/]
    [@b.select name="code.parent.id" label="上级级别" items=parents value=code.parent! empty="..."/]
    [@b.startend label="有效期"
      name="code.beginOn,code.endOn" required="true,false"
      start=code.beginOn end=code.endOn format="date"/]
    [@b.textfield name="code.remark" label="备注" value="${code.remark!}" maxlength="3"/]
    [@b.select name="code.module.id" label="模块" items=modules value=code.module! empty="..."/]
    [@b.select name="code.rank.id" label="课程属性" items=ranks value=code.rank! empty="..."/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
