[#ftl]
[@b.head/]
[@b.toolbar title="修改时间设置类型"]bar.addBack();[/@]
  [#assign sa][#if timeSetting.persisted]!update?id=${timeSetting.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="timeSetting.name" label="名称" value="${timeSetting.name!}" required="true" maxlength="20" /]
    [@b.textfield name="timeSetting.minutesPerUnit"  value=timeSetting.minutesPerUnit required="true" maxlength="3" /]
    [@b.select name="timeSetting.campus.id" label="校区" value="" style="width:200px;"
      value=(timeSetting.campus!) items=campuses option="id,name" empty="..."/]
    [@b.startend label="有效期" name="timeSetting.beginOn,timeSetting.endOn" start=timeSetting.beginOn! end=timeSetting.endOn! required="true,false"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
