[#ftl]
[@b.head/]
[@b.toolbar title="修改假日安排"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!update?id=${holiday.id}" theme="list"]
    [@b.textfield name="holiday.name" label="假日名称" value="${holiday.name!}" required="true" maxlength="20"/]
    [@b.startend label="生效失效时间" 
      name="holiday.beginOn,holiday.endOn" required="true,true" 
      start=holiday.beginOn end=holiday.endOn format="date"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]