[#ftl]
[@b.head/]
[@b.grid items=teachers var="teacher"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
    bar.addItem("导入",action.method('importForm'));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="staff.code" title="工号"]${teacher.code}[/@]
    [@b.col width="10%" property="staff.name" title="姓名"]
      [@b.a href="!info?id=${teacher.id}"]
        <span title="${teacher.beginOn!}~${teacher.endOn!}">${teacher.name}</span>
      [/@]
    [/@]
    [@b.col width="10%" property="staff.gender.name" title="性别"/]
    [@b.col property="department.name" title="院系"]${(teacher.department.name)!}[/@]
    [@b.col width="10%" property="staff.staffType.name" title="类别"]${(teacher.staff.staffType.name)!}[/@]
    [@b.col width="10%" property="staff.title.name" title="职称"]${(teacher.staff.title.name)!}[/@]
    [#if tutorTypes?size>0]
    [@b.col property="tutorType.name" width="10%" title="导师类别"/]
    [/#if]
    [@b.col width="8%" property="staff.external" title="是否外聘"]${teacher.staff.external?string('是','否')!}[/@]
    [@b.col width="8%" property="staff.parttime" title="是否兼职"]${teacher.staff.parttime?string('是','否')!}[/@]
    [@b.col width="10%" property="beginOn" title="任教起始"]${teacher.beginOn?string('yyyy-MM')}~${(teacher.endOn?string('yyyy-MM'))!'至今'}[/@]
  [/@]
[/@]
[@b.foot/]
