[#ftl]
[@b.head/]
[@b.grid items=departments var="department"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="code" title="代码"]${department.code}[/@]
    [@b.col property="name" title="名称"][@b.a href="!info?id=${department.id}"]${department.name}[/@][/@]
    [@b.col width="8%" property="shortName" title="简称"]${department.shortName!}[/@]
    [@b.col width="10%" property="category" title="类型"]${(department.category.name)!}[/@]
    [@b.col width="7%" property="teaching" title="教学部门"]${(department.teaching?string("是","否"))!}[/@]
    [@b.col width="7%" property="research" title="科研部门"]${(department.research?string("是","否"))!}[/@]
    [@b.col width="12%" title="校区"][#list department.campuses as c]${c.shortName!c.name}[#if c_has_next],[/#if][/#list][/@]
    [@b.col width="7%" property="indexno" title="序号"]${department.indexno}[/@]
    [@b.col width="15%" property="beginOn" title="生效时间"]${department.beginOn!}~${department.endOn!}[/@]
  [/@]
[/@]
[@b.foot/]
