[#ftl]
[@b.head/]
[@b.toolbar title="新建国家信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(code) theme="list"]
    [@b.textfield name="code.code" label="代码" value=code.code! required="true" maxlength="20"/]
    [@b.textfield name="code.name" label="名称" value=code.name! required="true" maxlength="200"/]
    [@b.textfield name="code.shortName" label="简称" value=code.shortName! maxlength="200"/]
    [@b.textfield name="code.enName" label="英文名" style="width:500px" value=code.enName! maxlength="200"/]
    [@b.textfield name="code.alpha2Code" label="2位字母代码" value=code.alpha2Code! required="true" maxlength="2"/]
    [@b.textfield name="code.alpha3Code" label="3位字母代码" value=code.alpha3Code! required="true" maxlength="3"/]
    [@b.startend label="有效期限"
      name="code.beginOn,code.endOn" required="true,false"
      start=code.beginOn end=code.endOn format="date"/]
    [@b.textfield name="code.remark" label="备注" value="${code.remark!}" maxlength="30"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
