[#ftl]
[@b.head/]
[@b.toolbar title="修改教室"]bar.addBack();[/@]
[#assign is_virtual][#if laboratory.persisted && !laboratory.roomNo??]1[#else]0[/#if][/#assign]
  [@b.form action=b.rest.save(laboratory) theme="list"]
    [@b.textfield name="laboratory.code" label="代码" value="${laboratory.code!}" required="true" maxlength="20"/]
    [@b.textfield name="laboratory.name" label="名称" value="${laboratory.name!}" required="true" maxlength="20"/]
    [@b.select name="laboratory.room.id" label="对应教室" value=laboratory.room!
               style="width:200px;" items=classrooms option="id,name" empty="..." /]
    [@b.startend label="有效期"  name="laboratory.beginOn,laboratory.endOn" required="true,false"
      start=laboratory.beginOn end=laboratory.endOn format="date"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit" /]
    [/@]
  [/@]
  [#list 1..10 as i]<br>[/#list]
[@b.foot/]
