[#ftl]
[@b.head/]
[@b.toolbar title="修改假日调课时间"]bar.addBack();[/@]
  [@b.form action=b.rest.save(holiday) theme="list"]
    [@b.textfield name="holiday.name" label="名称" value=holiday.name required="true" maxlength="20"/]
    [@b.date name="holiday.startOn" label="假日日期" value=holiday.startOn! required="true" /]
    [@b.date name="holiday.switchTo" label="调课到" value=holiday.switchTo! required="false"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
