[#ftl]
[@b.head/]
[@b.toolbar title="修改课程性质"]bar.addBack();[/@]
  [@b.form action=b.rest.save(courseNature) theme="list"]
    [@b.textfield name="courseNature.code" label="代码" value="${courseNature.code!}" required="true" maxlength="20"/]
    [@b.textfield name="courseNature.name" label="名称" value="${courseNature.name!}" required="true" maxlength="20"/]
    [@b.textfield name="courseNature.enName" label="英文名" value="${courseNature.enName!}" maxlength="100"/]
    [@b.radios label="是否实践课"  name="courseNature.practical" value=courseNature.practical items="1:common.yes,0:common.no"/]
    [@b.startend label="有效期"
      name="courseNature.beginOn,courseNature.endOn" required="true,false"
      start=courseNature.beginOn end=courseNature.endOn format="date"/]
    [@b.textfield name="courseNature.remark" label="备注" value="${courseNature.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
