[#ftl]
[@b.head/]
[@b.toolbar title="修改成绩类型"]bar.addBack();[/@]
  [@b.form action=b.rest.save(gradeType) theme="list"]
    [@b.textfield name="gradeType.code" label="代码" value="${gradeType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="gradeType.name" label="名称" value="${gradeType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="gradeType.enName" label="英文名" value="${gradeType.enName!}" maxlength="100"/]
    [@b.select label="考试类型"  name="gradeType.examType.id" value=gradeType.examType! items=examTypes/]
    [@b.startend label="有效期"
      name="gradeType.beginOn,gradeType.endOn" required="true,false"
      start=gradeType.beginOn end=gradeType.endOn format="date"/]
    [@b.textfield name="gradeType.remark" label="备注" value="${gradeType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
