[#ftl]
[@b.head/]
[@b.toolbar title="修改学习形式"]bar.addBack();[/@]
  [@b.form  theme="list" action=b.rest.save(studyType)]
    [@b.textfield name="studyType.code" label="代码" value="${studyType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="studyType.name" label="名称" value="${studyType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="studyType.enName" label="英文名" value="${studyType.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="studyType.beginOn,studyType.endOn" required="true,false"
      start=studyType.beginOn end=studyType.endOn format="date"/]
    [@b.textfield name="studyType.remark" label="备注" value="${studyType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
