[#ftl]
[@b.head/]
[@b.toolbar title="修改课程默认教材"]bar.addBack();[/@]
  [@b.form action=b.rest.save(courseTextbook) theme="list"]
    [@base.course label="课程" name="courseTextbook.course.id" value=courseTextbook.course! required="true" /]
    [@b.select label="教材" name="courseTextbook.textbook.id" value=courseTextbook.textbook! required="true" items=textbooks option=r"${item.isbn!} ${item.name!} ${item.author!} ${(item.press.name)!}" style="width:500px"/]
    [@b.radios label="是否推荐教材"  name="courseTextbook.recommended" value=courseTextbook.recommended items="1:common.yes,0:common.no" required="true"/]
    [@b.radios label="是否必选教材"  name="courseTextbook.required" value=courseTextbook.required items="1:common.yes,0:common.no" required="true"/]
    [@b.startend label="有效期"  name="courseTextbook.beginOn,courseTextbook.endOn" required="true,false"
      start=courseTextbook.beginOn end=courseTextbook.endOn format="date" style="width:100px"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
  [#list 1..10 as i]<br>[/#list]
[@b.foot/]
