[#ftl]
[@b.head/]
[@b.toolbar title="修改房间类型"]bar.addBack();[/@]
  [@b.form action=b.rest.save(roomType) theme="list"]
    [@b.textfield name="roomType.code" label="代码" value="${roomType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="roomType.name" label="名称" value="${roomType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="roomType.enName" label="英文名称" value="${roomType.enName!}" maxlength="100"/]
    [@b.startend label="有效期限"
      name="roomType.beginOn,roomType.endOn" required="true,false"
      start=roomType.beginOn end=roomType.endOn format="date"/]
    [@b.textfield name="roomType.remark" label="备注" value="${roomType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
