[#ftl]
[@b.head/]
[@b.toolbar title="修改教材获奖类型"]bar.addBack();[/@]
  [@b.form action=b.rest.save(bookAwardType) theme="list"]
    [@b.textfield name="bookAwardType.code" label="代码" value="${bookAwardType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="bookAwardType.name" label="名称" value="${bookAwardType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="bookAwardType.enName" label="英文名" value="${bookAwardType.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="bookAwardType.beginOn,bookAwardType.endOn" required="true,false"
      start=bookAwardType.beginOn end=bookAwardType.endOn format="date"/]
    [@b.textfield name="bookAwardType.remark" label="备注" value="${bookAwardType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
