[#ftl]
[@b.head/]
[@b.toolbar title="修改用户组信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(userGroup) theme="list"]
    [@b.textfield name="userGroup.indexno" label="层级编码" value=userGroup.indexno! required="true" maxlength="80"/]
    [@b.textfield name="userGroup.code" label="代码" value=userGroup.code! required="true" maxlength="30"/]
    [@b.textfield name="userGroup.name" label="名称" value=userGroup.name! required="true" maxlength="80"/]
    [@b.radios label="是否启用"  name="userGroup.enabled" value=userGroup.enabled items="1:common.yes,0:common.no"/]
    [@b.radios label="是否自动管理"  name="userGroup.autoManage" value=userGroup.autoManage items="1:common.yes,0:common.no"/]
    [@b.select label="上级组" name="userGroup.parent.id" value=(userGroup.parent)! style="width:200px;"  items=parents  empty="..."/]
    [@b.textfield name="userGroup.remark" label="说明" value=userGroup.remark! maxlength="190"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
