[#ftl]
[@b.head/]
[@b.toolbar title="修改学科门类类型"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if disciplineCategory.persisted]!update?id=${disciplineCategory.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="disciplineCategory.code" label="代码" value="${disciplineCategory.code!}" required="true" maxlength="20"/]
    [@b.textfield name="disciplineCategory.name" label="名称" value="${disciplineCategory.name!}" required="true" maxlength="20"/]
    [@b.textfield name="disciplineCategory.enName" label="英文名称" value="${disciplineCategory.enName!}" maxlength="100"/]
    [@b.startend label="有效期限"
      name="disciplineCategory.beginOn,disciplineCategory.endOn" required="false,false"
      start=disciplineCategory.beginOn end=disciplineCategory.endOn format="date"/]
    [@b.textfield name="disciplineCategory.remark" label="备注" value="${disciplineCategory.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
