[#ftl]
[@b.head/]
[@b.toolbar title="修改课程种类代码"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if courseCategory.persisted]!update?id=${courseCategory.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="courseCategory.code" label="代码" value="${courseCategory.code!}" required="true" maxlength="20"/]
    [@b.textfield name="courseCategory.name" label="名称" value="${courseCategory.name!}" required="true" maxlength="20"/]
    [@b.textfield name="courseCategory.enName" label="英文名" value="${courseCategory.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="courseCategory.beginOn,courseCategory.endOn" required="true,false"
      start=courseCategory.beginOn end=courseCategory.endOn format="date"/]
    [@b.textfield name="courseCategory.remark" label="备注" value="${courseCategory.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
