[#ftl]
[@b.head/]
[@b.toolbar title="教职工类型"]bar.addBack();[/@]
  [@b.form action=b.rest.save(staffSourceType) theme="list"]
    [@b.textfield name="staffSourceType.code" label="代码" value="${staffSourceType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="staffSourceType.name" label="名称" value="${staffSourceType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="staffSourceType.enName" label="英文名" value="${staffSourceType.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="staffSourceType.beginOn,staffSourceType.endOn" required="true,false"
      start=staffSourceType.beginOn end=staffSourceType.endOn format="date"/]
    [@b.textfield name="staffSourceType.remark" label="备注" value="${staffSourceType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
