[#ftl]
[@b.head/]
[@b.toolbar title="职称等级"]bar.addBack();[/@]
  [@b.form action=b.rest.save(professionalGrade) theme="list"]
    [@b.textfield name="professionalGrade.code" label="代码" value="${professionalGrade.code!}" required="true" maxlength="20"/]
    [@b.textfield name="professionalGrade.name" label="名称" value="${professionalGrade.name!}" required="true" maxlength="20"/]
    [@b.textfield name="professionalGrade.enName" label="英文名" value="${professionalGrade.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="professionalGrade.beginOn,professionalGrade.endOn" required="true,false"
      start=professionalGrade.beginOn end=professionalGrade.endOn format="date"/]
    [@b.textfield name="professionalGrade.remark" label="备注" value="${professionalGrade.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
