[#ftl]
[@b.head/]
[@b.toolbar title="修改课时类别代码"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if courseHourType.persisted]!update?id=${courseHourType.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="courseHourType.code" label="代码" value="${courseHourType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="courseHourType.name" label="名称" value="${courseHourType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="courseHourType.enName" label="英文名" value="${courseHourType.enName!}" maxlength="100"/]
    [#assign categoryTitles={}/]
    [#list categories as ca]
      [#assign categoryTitles=categoryTitles+{'${ca}':'${ca.title}'}/]
    [/#list]
    [@b.radios label="分类" name="courseHourType.category" items=categoryTitles value=(courseHourType.category?string)!'Lecture'/]
    [@b.startend label="有效期"
      name="courseHourType.beginOn,courseHourType.endOn" required="true,false"
      start=courseHourType.beginOn end=courseHourType.endOn format="date"/]
    [@b.textfield name="courseHourType.remark" label="备注" value="${courseHourType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
