[#ftl]
[@b.head/]
[@b.toolbar title="修改专业"]bar.addBack();[/@]
[@b.tabs]
  [@b.tab label="基本信息"]
  [#assign sa][#if major.persisted]!update?id=${major.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="major.code" label="代码" value="${major.code!}" required="true" maxlength="20"/]
    [@b.textfield name="major.name" label="名称" value="${major.name!}" required="true" maxlength="20"/]
    [@b.textfield name="major.enName" label="英文名" value="${major.enName!}" maxlength="100"/]
    [@b.textfield name="major.shortName" label="简称" value="${major.shortName!}" maxlength="100"/]
    [@b.startend label="有效期"   name="major.beginOn,major.endOn" required="true,false" start=major.beginOn end=major.endOn format="date" style="width:100px"/]
    [@b.textfield name="major.remark" label="备注" value="${major.remark!}" maxlength="30"/]
    [@b.formfoot]
      <input type="hidden" name="major.project.id" value="${major.project.id}"/>
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
   [/@]
 [/@]
  [#if major.persisted]
    [@b.tab label="建设过程"]
      [@b.div href="major-journal!search?majorJournal.major.id=${major.id}"/]
    [/@]
    [@b.tab label="学习年限"]
      [@b.div href="school-length!search?schoolLength.major.id=${major.id}"/]
    [/@]
    [@b.tab label="专业学科信息"]
      [@b.div href="major-discipline!search?majorDiscipline.major.id=${major.id}"/]
    [/@]
  [/#if]
  [/@]
[@b.foot/]
