[#ftl]
[@b.head/]
[@b.toolbar title="修改成绩记录方式"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if gradingMode.persisted]!update?id=${gradingMode.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="gradingMode.code" label="代码" value="${gradingMode.code!}" required="true" maxlength="20"/]
    [@b.textfield name="gradingMode.name" label="名称" value="${gradingMode.name!}" required="true" maxlength="20"/]
    [@b.textfield name="gradingMode.enName" label="英文名" value="${gradingMode.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="gradingMode.beginOn,gradingMode.endOn" required="true,false"
      start=gradingMode.beginOn end=gradingMode.endOn format="date"/]
    [@b.textfield name="gradingMode.remark" label="备注" value="${gradingMode.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
