[#ftl]
[@b.head/]
[@b.grid items=schools var="school"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="code" title="代码"]${school.code}[/@]
    [@b.col property="name" title="名称"]${school.name}[/@]
    [@b.col width="15%" property="category.name" title="办学类型"/]
    [@b.col width="15%" property="division.name" title="所在地区"/]
    [@b.col width="15%" property="superiorOrg" title="上级部门"/]
  [/@]
[/@]
[@b.foot/]
