[#ftl]
[@b.head/]
[@b.toolbar title="修改项目"]bar.addBack();[/@]
[@b.tabs]
  [@b.tab label="项目维护"]
  [@b.form action=b.rest.save(project) theme="list"]
    [@b.textfield name="project.name" label="名称" value="${project.name!}" required="true" maxlength="20"/]
    [@b.textfield name="project.code" label="代码" value="${project.code!}" required="true" maxlength="20"/]
    [@b.select name="project.school.id" label="适用学校" value="${(project.school.id)!}" required="true" items=schools/]
    [@b.select label="校区列表" name="campus.id" items=campuses values=project.campuses required="true" width="400px" multiple="true"/]
    [@b.select label="院系列表" name="department.id" items=departments values=project.departments required="true" width="800px" multiple="true"/]
    [@b.select label="培养类型" name="eduType.id" items=eduTypes values=project.eduTypes width="400px" required="true"  multiple="true"/]
    [@b.select label="培养层次" name="level.id" items=levels values=project.levels width="400px" required="true"  multiple="true"/]
    [@b.select label="学生分类" name="stdLabel.id" items=stdLabels values=project.stdLabels width="400px" required="false"  multiple="true"/]
    [@b.select label="学生类别" name="stdType.id" items=stdTypes values=project.stdTypes required="false"  multiple="true"/]
    [@b.select label="使用校历" name="project.calendar.id" value= project.calendar! required="true" items=calendars /]
    [@b.radios label="是否辅修"  name="project.minor" value=project.minor items="1:common.yes,0:common.no"/]
    [@b.select label="类型" name="project.category.id" value=project.category! required="true"
               style="width:200px;" items=eduCategories empty="..."/]
    [@b.textarea name="project.description" label="描述" value=project.description! required="true" maxlength="2000" /]
    [@b.textfield name="project.administration" label="主管部门" value=project.administration! required="true" maxlength="80"/]
    [@b.textfield name="project.administration2nd" label="二级部门称呼" value=project.administration2nd! maxlength="80"/]
    [@b.startend label="有效期"
      name="project.beginOn,project.endOn" required="true,false"
      start=project.beginOn end=project.endOn format="date"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
  [/@]
  [#if project.persisted]
  [@b.tab label="项目配置"]
    [@b.div href="project-property!search?projectProperty.project.id=${project.id}&orderBy=projectProperty.name asc"/]
  [/@]
  [@b.tab label="基础代码配置"]
    [@b.div href="project-code!search?projectCode.project.id=${project.id}"/]
  [/@]
  [/#if]
[/@]
[@b.foot/]
