[#ftl]
[@b.head/]
[@b.grid items=examStatuses var="examStatus"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="15%" property="code" title="代码"]${examStatus.code}[/@]
    [@b.col width="15%" property="name" title="名称"][@b.a href="!info?id=${examStatus.id}"]${examStatus.name}[/@][/@]
    [@b.col width="15%" property="enName" title="英文名"]${examStatus.enName!}[/@]
    [@b.col width="8%" property="attended" title="是否参加考试"]${(examStatus.attended?string("是","否"))!}[/@]
    [@b.col width="8%" property="hasDeferred" title="是否缓考"]${(examStatus.hasDeferred?string("是","否"))!}[/@]
    [@b.col width="9%" property="cheating" title="是否有作弊行为"]${(examStatus.cheating?string("是","否"))!}[/@]
    [@b.col width="10%" property="beginOn" title="生效日期"]${examStatus.beginOn!}[/@]
    [@b.col width="10%" property="endOn" title="失效日期"]${examStatus.endOn!}[/@]
  [/@]
[/@]
[@b.foot/]
