[#ftl]
[@b.head/]
[@b.toolbar title="修改教材类型"]bar.addBack();[/@]
  [@b.form action=b.rest.save(bookType) theme="list"]
    [@b.textfield name="bookType.code" label="代码" value="${bookType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="bookType.name" label="名称" value="${bookType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="bookType.enName" label="英文名" value="${bookType.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="bookType.beginOn,bookType.endOn" required="true,false"
      start=bookType.beginOn end=bookType.endOn format="date"/]
    [@b.textfield name="bookType.remark" label="备注" value="${bookType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
