[#ftl]
[@b.head/]
[@b.toolbar title="新建通用人员信息"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!save" theme="list"]
    [@b.textfield name="user.code" label="学工号" value="${user.code!}" required="true" maxlength="30"/]
    [@b.textfield name="user.name" label="姓名" value="${user.name!}" required="true" maxlength="80"/]
    [@b.select name="user.department.id" label="所在部门" value="${user.department!}" 
               style="width:200px;" href=urp.service("/base/departments") empty="..."/]
    [@b.select name="user.category.id" label="人员分类" value="${user.category!}" style="width:200px;" 
        href=urp.service("/base/code/user-categories")/]
    [@b.textfield name="user.mobile" label="电话" value="${user.mobile!}" maxlength="15"/]
    [@b.textfield name="user.email" label="邮箱" value="${user.email!}" required="true" maxlength="80"/]
    [@b.textfield name="user.remark" label="说明" value="${user.remark!}" maxlength="190"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]