[#ftl]
[@b.head/]
[@b.toolbar title="修改学籍异动类型"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if stdAlterType.persisted]!update?id=${stdAlterType.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="stdAlterType.code" label="代码" value="${stdAlterType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="stdAlterType.name" label="名称" value="${stdAlterType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="stdAlterType.enName" label="英文名" value="${stdAlterType.enName!}" maxlength="100"/]
    [@b.startend label="有效期"
      name="stdAlterType.beginOn,stdAlterType.endOn" required="true,false"
      start=stdAlterType.beginOn end=stdAlterType.endOn format="date"/]
    [@b.textfield name="stdAlterType.remark" label="备注" value="${stdAlterType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
